---
title: "regression"
output: html_notebook
---

# Introduction

This is about regression, we are about to perform regression analysis using marketing data of the datarium package in r.

```{r}
library(tidyverse)
library("caret")
theme_set(theme_bw())
```

```{r}
# Load the data
data("marketing", package = "datarium")
# Inspect the data
sample_n(marketing, 3)
```

```{r}
# Install packages if not yet installed
library(tidyverse) # loading tidyverse
library("caret") # loading caret
theme_set(theme_bw()) #I don't know
```
```{r}
# Load the data
data("marketing", package = "datarium")
# Inspect the data
sample_n(marketing, 3)
```

```{r}
#  install datarium if not yet installed at console 
install.packages("datarium") # installing datarium
library(datarium) # loading datarium
```

```{r}
# Load the data
data("marketing", package = "datarium")
# Inspect the data
sample_n(marketing, 3)
```

```{r}
# Split the data into training and test set
set.seed(123)
training.samples <- marketing$sales %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- marketing[training.samples, ]
test.data <- marketing[-training.samples, ]
```

```{r}
# Build the model
model <- lm(sales ~., data = train.data)
# Summarize the model
summary(model)
# Make predictions
predictions <- model %>% predict(test.data)
# Model performance
# (a) Prediction error, RMSE
RMSE(predictions, test.data$sales)
# (b) R-square
R2(predictions, test.data$sales)
```

```{r}
# Predicting with new data
# using the model
youtube <- 0
facebook <- 90
newspaper <- 0
a <- data.frame(youtube,facebook,newspaper)
p <- model %>% predict(a)
p
```

Our model is as follows:
$$\hat{y} = 3.59 + 0.04x_1 + 0.19x_2 + \epsilon$$
where $\hat{y}$ is sales, and $x_1$ is youtube, $x_2$ is facebook, and $\epsilon$ is the error term.









```{r}

```

